"""BrowserSession tests: launch, observation, dialogs and tabs.

They run headless against the bundled local store (``fixture_site``) - no
network, no API keys.  The session is addressed the way the agent addresses it:
element ids come from a snapshot, and the CSS that resolves an id is generated by
``selector_for`` (never a hand-written selector).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from webpilot.browser.actions import selector_for
from webpilot.browser.session import BrowserSession, snapshot_js
from webpilot.tokenizer import count_tokens


def element_named(model, name: str, role: str | None = None):
    for element in model.elements:
        if name.lower() in element.name.lower() and (role is None or element.role == role):
            return element
    return None


# --------------------------------------------------------------------------- #
# launch configuration (no browser needed)
# --------------------------------------------------------------------------- #

def test_launch_options_headless(make_config):
    config = make_config(headless=True, window_size=(1024, 768))
    options = BrowserSession(config).launch_options()

    assert options["headless"] is True
    assert options["args"][:2] == ["--no-sandbox", "--disable-dev-shm-usage"]
    assert "--start-maximized" not in options["args"]
    assert options["viewport"] == {"width": 1024, "height": 768}
    assert options["user_data_dir"] == str(config.user_data_dir)
    assert "channel" not in options


def test_launch_options_headful_uses_the_real_window(make_config):
    config = make_config(headless=False, browser_channel="chrome",
                         browser_args=["--lang=en-GB"])
    options = BrowserSession(config).launch_options()

    assert options["headless"] is False
    assert "--start-maximized" in options["args"]
    assert options["viewport"] is None, "a maximised window must decide the viewport"
    assert "--lang=en-GB" in options["args"]
    assert options["channel"] == "chrome"


def test_sniffers_javascript_is_a_single_idempotent_iife():
    source = snapshot_js()

    assert source.lstrip().startswith("/*")
    assert source.rstrip().endswith(")()")
    assert "shadowRoot" in source and "iframe" in source
    assert "__webpilotInstalled" in source, "the error collector must install once"


# --------------------------------------------------------------------------- #
# observation
# --------------------------------------------------------------------------- #

def test_sniffer_finds_the_search_box(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/search")
    model = browser_session.snapshot(budget_tokens=1200)

    box = element_named(model, "Search products", role="textbox")
    assert box is not None, [el.line() for el in model.elements]
    assert box.tag == "input"
    assert box.placeholder == "Search products"
    assert box.in_viewport is True
    assert box.id > 0
    assert model.generation >= 1
    assert model.html_chars > 500, "the sniffer reports how much html it did NOT send"
    # the page block we would send is a tiny fraction of the html we looked at
    from webpilot.browser.snapshot import render_page_model

    assert count_tokens(render_page_model(model, budget_tokens=1200)) < model.html_chars / 4


def test_submitting_a_search_updates_what_the_sniffer_sees(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/search")
    model = browser_session.snapshot(budget_tokens=1200)
    box = element_named(model, "Search products", role="textbox")

    field = browser_session.page.locator(selector_for(box.id)).first
    field.press_sequentially("desk", delay=0)
    field.press("Enter")
    browser_session.page.wait_for_load_state("load")

    after = browser_session.snapshot(budget_tokens=1200)
    assert "q=desk" in after.url
    assert "Results for desk" in after.text
    assert element_named(after, "Standing Desk") is not None
    assert "Monitor Arm" not in after.text, "search results should be filtered"


def test_generation_advances_and_delta_sees_the_changes(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/search")
    first = browser_session.snapshot(budget_tokens=1200)
    second = browser_session.snapshot(budget_tokens=1200, mode="delta")

    assert second.generation == first.generation + 1
    assert second.url == first.url
    assert len(second.elements) == len(first.elements)

    browser_session.goto(f"{fixture_site}/cart")
    third = browser_session.snapshot(budget_tokens=1200, mode="delta")
    # a navigation must not be rendered as a delta of the previous page
    assert third.url.endswith("/cart")
    assert third.url != second.url
    assert third.generation == second.generation + 1
    assert "Your cart is empty" in third.text


def test_snapshotting_twice_reuses_the_ids(browser_session, fixture_site):
    browser_session.goto(fixture_site)
    first = browser_session.snapshot(budget_tokens=1200)
    second = browser_session.snapshot(budget_tokens=1200)

    assert [(el.id, el.role, el.name) for el in first.elements] == \
        [(el.id, el.role, el.name) for el in second.elements]
    assert second.page_hash() == first.page_hash(), "the sniffer must be idempotent"


def test_ids_are_never_recycled_after_a_navigation(browser_session, fixture_site):
    """A stale id must stay unresolvable - otherwise a click could hit a stranger."""
    browser_session.goto(fixture_site)
    first = browser_session.snapshot(budget_tokens=1200)

    browser_session.goto(f"{fixture_site}/cart")
    second = browser_session.snapshot(budget_tokens=1200)

    assert min(el.id for el in second.elements) > max(el.id for el in first.elements)
    assert not ({el.id for el in first.elements} & {el.id for el in second.elements})


def test_shadow_dom_elements_are_found(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/shadow")
    model = browser_session.snapshot(budget_tokens=1500)

    shadow_button = element_named(model, "Shadow action", role="button")
    assert shadow_button is not None, [el.line() for el in model.elements]
    assert shadow_button.frame == 0
    assert "Inside the shadow root" in model.text


def test_iframe_elements_get_their_own_frame_index(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/iframe")
    model = browser_session.snapshot(budget_tokens=2000)

    assert len(model.frames) >= 2
    assert model.frames[1].endswith("/frame")
    note = element_named(model, "Note", role="textbox")
    assert note is not None, [el.line() for el in model.elements]
    assert note.frame == 1
    save = element_named(model, "Save note", role="submit")
    assert save is not None and save.frame == 1
    # main-frame and frame elements are both present, each with its own index
    assert {el.frame for el in model.elements} == {0, 1}


def test_native_dialogs_are_recorded_and_never_hang(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/account")
    model = browser_session.snapshot(budget_tokens=1200)
    button = element_named(model, "Order history", role="button")
    assert button is not None

    browser_session.page.locator(selector_for(button.id)).first.click()

    assert browser_session.pending_dialogs, "the dialog handler must record the text"
    seen = browser_session.snapshot(budget_tokens=1200)
    assert any("Order history is empty" in dialog for dialog in seen.dialogs)
    assert browser_session.pending_dialogs == [], "dialogs are reported once"


def test_console_errors_are_collected_once(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/errors")
    browser_session.snapshot(budget_tokens=800)
    browser_session.page.wait_for_timeout(400)
    model = browser_session.snapshot(budget_tokens=800)

    assert any("boom from the page" in error for error in model.errors), model.errors


def test_is_blocked_by_auth_heuristic(browser_session, fixture_site):
    browser_session.goto(f"{fixture_site}/login")
    browser_session.snapshot(budget_tokens=1200)
    assert browser_session.is_blocked_by_auth() is True

    browser_session.goto(fixture_site)
    assert browser_session.is_blocked_by_auth() is False


def test_raw_text_and_raw_html_are_bounded_and_for_extraction_only(browser_session, fixture_site):
    browser_session.goto(fixture_site)
    html = browser_session.raw_html()
    text = browser_session.raw_text()

    assert html.lower().startswith("<!doctype html")
    assert "Workspace gear" in text
    assert len(browser_session.raw_html(max_chars=200)) == 200
    assert len(browser_session.raw_text(max_chars=40)) == 40
    docstring = BrowserSession.raw_html.__doc__ or ""
    assert "Extractor" in docstring, "the raw accessors must warn the main loop off"


def test_screenshot_writes_into_the_configured_directory(browser_session, config, fixture_site):
    browser_session.goto(fixture_site)
    path = browser_session.screenshot("unit-test")

    assert Path(path).exists()
    assert Path(path).parent == Path(config.screenshot_dir)
    assert Path(path).stat().st_size > 0
    assert browser_session.last_model is None or browser_session.last_model.screenshot_path == path


# --------------------------------------------------------------------------- #
# tabs and lifecycle
# --------------------------------------------------------------------------- #

def test_tabs_open_switch_and_close(browser_session, fixture_site):
    browser_session.new_page(f"{fixture_site}/cart")

    assert len(browser_session.pages) == 2
    infos = browser_session.tab_infos()
    assert [info.index for info in infos] == [0, 1]
    assert infos[1].active is True and infos[1].url.endswith("/cart")

    browser_session.switch(0)
    assert browser_session.tab_infos()[0].active is True
    assert browser_session.page.url.rstrip("/") == fixture_site.rstrip("/")

    browser_session.close_page(1)
    assert len(browser_session.pages) == 1


def test_stop_is_idempotent_and_snapshot_afterwards_is_refused(browser_session, fixture_site):
    browser_session.stop()
    browser_session.stop()

    from webpilot.errors import BrowserError

    with pytest.raises(BrowserError):
        browser_session.snapshot(budget_tokens=400)
