"""The browser layer: page sniffer, session, page model and action execution.

Typical use::

    from webpilot.browser import BrowserSession, ActionExecutor

    session = BrowserSession(config, ui)
    session.start()
    session.new_page("https://example.com")
    model = session.snapshot(budget_tokens=config.page_token_budget)
    executor = ActionExecutor(session, config)
    result = executor.execute(ToolCall("click", {"element_id": model.elements[0].id}))

Nothing in this package knows a URL path or a CSS class of any particular site:
the page sniffer hands out integer ids, and the selector that addresses an id is
generated by :func:`webpilot.browser.actions.selector_for`.
"""

from __future__ import annotations

from .actions import AGENT_LOCAL_TOOLS, WEBPILOT_ATTR, ActionExecutor, selector_for
from .session import BrowserSession, snapshot_js
from .snapshot import build_page_model, render_page_model

__all__ = [
    "AGENT_LOCAL_TOOLS",
    "ActionExecutor",
    "BrowserSession",
    "WEBPILOT_ATTR",
    "build_page_model",
    "render_page_model",
    "selector_for",
    "snapshot_js",
]
